### ISSUE TITLE
Drag names from left database/table area to script

### ISSUE THREAD

**Issue by jmacagno** [ScriptPup/sqltools-teradata-driver#10]
Allow developers to drag the names of database objects in the SQL script editor.

**Comment by ScriptPup** [comment]
I think this would have to be an enhancement over on the [sqltools base project](https://github.com/mtxr/vscode-sqltools), I don't believe this is a feature present in sqltools as a whole at this point. I'll check to see if it's something I can implement independently, but most things that interact with the browser are at the layer above.

I see that there are now active developers with approval and merge permissions again which is great news, we should be able to put together a pull request if nothing else. Things have been pretty hectic recently so I can't promise to get to it on my side very soon, but I'll give it a shot when I can.

**Comment by ScriptPup** [comment]
Created feature request https://github.com/mtxr/vscode-sqltools/issues/1135.

Will look at it myself and give it a shot. So far I'm having just about no luck getting the base dev branch to install dependencies even though, so we'll see.

**Comment by ScriptPup** [comment]
PR for the requested feature has been submitted - Closing this enhancement request out as it's now out of my hands. Once the PR is merged, then the feature will be available for *all* sqltools plugins. 

If the PR is merged before VSCode version `1.78` is released, then the functionality will be available only to users with `VSCode insiders` installed. Once version `1.78` is released, then the feature will be fully available.

![efe6d2a6-70cf-4976-a5aa-3e38d924b328](https://user-images.githubusercontent.com/6163646/235359426-ed5448c9-9d3c-4003-ba04-1d649b61dd59.gif)
