### ISSUE TITLE
Ability to select Indiviual Cells in Result Set

### ISSUE THREAD

**Issue by jimboug** [ScriptPup/sqltools-teradata-driver#14]
When selecting within a resultset only the whole row can be selected, this does not allow for cell copy and paste

Request the ability to select a cell at a time

**Comment by ScriptPup** [comment]
I think this may have been something added/fixed in the top level project.
![1b08922a-fa1a-4e84-8527-f6f2cb8c630a](https://user-images.githubusercontent.com/6163646/233800606-e5d55345-6048-4593-a064-4f8781465b5f.gif)
