### ISSUE TITLE
Ability to see Teradata Error Codes

### ISSUE THREAD

**Issue by jimboug** [ScriptPup/sqltools-teradata-driver#15]
Any failed queries give generic error codes, request the Teradata specific error code be returned

**Comment by ScriptPup** [comment]
Implemented. Will be published with 0.4.0 package.

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/6163646/233806351-a05d7ee7-ea65-4651-a8e7-4ba9d22c503c.png">
