### ISSUE TITLE
Show DBC within the Database List on the Left

### ISSUE THREAD

**Issue by jimboug** [ScriptPup/sqltools-teradata-driver#16]
After logging in all databases are shown apart from DBC, which hinders the ability to see DBC table and view list

**Comment by ScriptPup** [comment]
A toggle should be added to the connection definition to show/hide DBC tables. Most users will likely find system tables showing up to be unnecessary. Only admin/power users will need this, so we should have the option available.

**Comment by ScriptPup** [comment]
Implemented. Will be published with 0.4.0 package.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/6163646/233805095-11f9fb84-0d72-4cb4-a34d-143b0b558803.png">


<img width="251" alt="image" src="https://user-images.githubusercontent.com/6163646/233804676-ffab995a-0782-4818-8582-dc5279f31c66.png">
