### ISSUE TITLE
Ability to move results set window

### ISSUE THREAD

**Issue by jimboug** [ScriptPup/sqltools-teradata-driver#17]
The results set window cannot be undocked,

Request the ability to move the result set window under the sql query window

**Comment by ScriptPup** [comment]
It's possible to move any of the VSCode windows to pretty much any position:
![f0dee2f6-c58a-44ba-8e20-20456dfb7dcb](https://user-images.githubusercontent.com/6163646/233800659-327e1c75-a808-44cd-bac2-d0946408b9cd.gif)
